model:
  class_path: modules.ImagePASegmentNetModule
  init_args:
    pointnet_emd_dim: 512
    max_num_parts: 20
    max_num_similar_parts: 20
    img_size: 224
data:
  data_features:
    - img
    - pts
    - masks
    - similar_parts_cnt
    - bbox_size
    - ins_one_hot
  normalize_img: False
optimizer:
  class_path: AdamW
  init_args:
    lr: 1e-3
    weight_decay: 1e-5
lr_scheduler:
  class_path: StepLR
  init_args:
    step_size: 50
    gamma: 0.9
trainer:
  max_epochs: 1000
  log_every_n_steps: 100
