model:
  class_path: modules.ManualPAAssemblyNetModule
  init_args:
    loss_weight_center: 0.0
    loss_weight_quat: 0.0
    loss_weight_l2_rot: 0.0
    loss_weight_shape_chamfer: 0.0
    loss_weight_mask: 0.0
    loss_weight_permutation: 1.0
    order_mode: learned
    eval_assembly: false
    eval_permutation: true
    save_poses: false
    save_metrics: false
    save_orders: true
data:
  data_features:
    - imgs
    - pts
    - similar_parts_cnt
    - order
    - group
    - parts_cam_dof
  step_mode: lastonly
  max_parts_per_batch: 128
  val_split_pathname: splits/image_pa/chair.test.txt
  test_split_pathname: splits/image_pa/chair.test.txt
optimizer:
  class_path: AdamW
  init_args:
    lr: 1e-5
    weight_decay: 1e-4
lr_scheduler:
  class_path: StepLR
  init_args:
    step_size: 5
    gamma: 0.9
trainer:
  max_epochs: 50
  gradient_clip_val: 20
  callbacks:
    # https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.ModelCheckpoint.html#lightning.pytorch.callbacks.ModelCheckpoint
    - class_path: ModelCheckpoint
      init_args:
        filename: epoch={epoch:02d}-KD={validate/KD:.4f}
        monitor: validate/KD
        verbose: false
        save_last: true
        save_top_k: 1
        mode: max
        auto_insert_metric_name: false
    # https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.LearningRateMonitor.html#lightning.pytorch.callbacks.LearningRateMonitor
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch